// example-vue/src/App.vue
<script setup lang="ts">
import { ref, provide } from "vue";
import ElementPanel from "./components/ElementPanel.vue";
import Toolbar from "./components/Toolbar.vue";
import DesignCanvas from "./components/DesignCanvas.vue";
import PropertyPanel from "./components/PropertyPanel.vue";
import PreviewModal from "./components/PreviewModal.vue";
import { useKuprint } from "./composables/useKuprint";
import { useDesignerStore } from "./stores/designer";

const store = useDesignerStore();

// templateRef → kuprint 设计面板挂载点（位于 DesignCanvas 区域）
// optionsRef → kuprint 属性编辑器挂载点（位于 PropertyPanel 区域）
const templateRef = ref<HTMLElement>();
const optionsRef = ref<HTMLElement>();

// 初始化 kuprint 并注入 API 给所有子组件（Toolbar, PreviewModal 等需要）
const kuprintApi = useKuprint(templateRef, optionsRef);
provide("kuprint", kuprintApi);
</script>

<template>
  <div class="demo-layout">
    <!-- 左侧：拖拽元素面板 -->
    <ElementPanel />

    <!-- 中间：工具栏 + 设计面板 + 输出 -->
    <div class="demo-layout-content">
      <Toolbar />

      <DesignCanvas>
        <!-- kuprint 设计面板挂载到此容器 -->
        <div
          id="kuprint-printTemplate"
          ref="templateRef"
          class="kuprint-printTemplate"
          style="margin-top: 15px"
        ></div>
      </DesignCanvas>
    </div>

    <!-- 右侧：属性编辑面板 -->
    <PropertyPanel>
      <!-- kuprint 属性编辑器挂载到此容器 -->
      <div id="PrintElementOptionSetting" ref="optionsRef">
        <p style="color: #999; font-size: 13px; text-align: center; margin-top: 20px">
          点击设计面板中的元素<br />
          在此编辑属性
        </p>
      </div>
    </PropertyPanel>

    <!-- 预览弹窗 -->
    <PreviewModal v-if="store.showPreview" />
  </div>
</template>

// example-react/src/App.tsx
/**
 * App.tsx — 应用根组件
 *
 * 使用 React 19 + React Compiler 优化性能。
 * 状态管理使用 Zustand。
 */

import { ElementPanel } from "@/components/ElementPanel";
import { Toolbar } from "@/components/Toolbar";
import { DesignCanvas } from "@/components/DesignCanvas";
import { PropertyPanel } from "@/components/PropertyPanel";
import { PreviewModal } from "@/components/PreviewModal";
import { useKuprint } from "@/hooks/useKuprint";
import { useDesignerStore } from "@/stores/designer";

export default function App() {
  const kuprintApi = useKuprint();
  const showPreview = useDesignerStore((s) => s.showPreview);

  return (
    <div className="demo-layout">
      {/* 左侧：拖拽元素面板 */}
      <ElementPanel />

      {/* 中间：工具栏 + 设计面板 + 输出 */}
      <div className="demo-layout-content">
        <Toolbar api={kuprintApi} />

        <DesignCanvas>
          {/* kuprint 设计面板挂载到此容器 */}
          <div
            id="kuprint-printTemplate"
            ref={kuprintApi.templateRef}
            className="kuprint-printTemplate"
            style={{ marginTop: 15 }}
          />
        </DesignCanvas>
      </div>

      {/* 右侧：属性编辑面板 */}
      <PropertyPanel>
        {/* kuprint 属性编辑器挂载到此容器 */}
        <div id="PrintElementOptionSetting" ref={kuprintApi.optionsRef}>
          <p
            style={{
              color: "#999",
              fontSize: 13,
              textAlign: "center",
              marginTop: 20,
            }}
          >
            点击设计面板中的元素
            <br />
            在此编辑属性
          </p>
        </div>
      </PropertyPanel>

      {/* 预览弹窗 */}
      {showPreview && <PreviewModal api={kuprintApi} />}
    </div>
  );
}
