// example-vue/src/components/PreviewModal.vue
<script setup lang="ts">
/**
 * PreviewModal.vue — 打印预览弹窗（纯 CSS 实现）
 */
import { useDesignerStore } from "@/stores/designer";
import { inject } from "vue";

const store = useDesignerStore();
const { printPreviewHtml } = inject("kuprint") as any;

function close() {
  store.togglePreview(false);
}

function handlePrint() {
  printPreviewHtml();
}
</script>

<template>
  <div class="demo-modal-overlay" @click.self="close">
    <div class="demo-modal">
      <div class="demo-modal-header">
        <h4 class="demo-modal-title">打印预览</h4>
        <button class="demo-modal-close" @click="close">&times;</button>
      </div>
      <div class="demo-modal-body">
        <div class="demo-mb-10">
          <button class="demo-btn demo-btn-danger" @click="handlePrint">打印</button>
        </div>
        <div class="prevViewDiv" v-html="store.previewHtml"></div>
      </div>
      <div class="demo-modal-footer">
        <button class="demo-btn" @click="close">关闭</button>
      </div>
    </div>
  </div>
</template>

// example-react/src/components/PreviewModal.tsx
/**
 * PreviewModal.tsx — 打印预览弹窗（纯 CSS 实现）
 */

import { useDesignerStore } from "@/stores/designer";

interface KuprintApi {
  printPreviewHtml: () => void;
}

export function PreviewModal({ api }: { api: KuprintApi }) {
  const previewHtml = useDesignerStore((s) => s.previewHtml);
  const togglePreview = useDesignerStore((s) => s.togglePreview);

  function close() {
    togglePreview(false);
  }

  function handlePrint() {
    api.printPreviewHtml();
  }

  return (
    <div className="demo-modal-overlay" onClick={close}>
      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */}
      <div className="demo-modal" onClick={(e) => e.stopPropagation()}>
        <div className="demo-modal-header">
          <h4 className="demo-modal-title">打印预览</h4>
          <button className="demo-modal-close" onClick={close}>
            &times;
          </button>
        </div>
        <div className="demo-modal-body">
          <div className="demo-mb-10">
            <button className="demo-btn demo-btn-danger" onClick={handlePrint}>
              打印
            </button>
          </div>
          <div className="prevViewDiv" dangerouslySetInnerHTML={{ __html: previewHtml }} />
        </div>
        <div className="demo-modal-footer">
          <button className="demo-btn" onClick={close}>
            关闭
          </button>
        </div>
      </div>
    </div>
  );
}
